version: "3"
services:
  db:
    container_name: labDB
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - labrez
  backend:
    depends_on:
      - db
    build: ./
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - labrez
  frontend:
    depends_on:
      - db
      - backend
    build: ./fe-src
    ports:
      - '3000:80'
    networks:
      - labrez
volumes:
  db:
    driver: local
networks:
  labrez:
    driver: bridge